# Generated by Django 3.2.10 on 2021-12-12 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0002_alter_cat_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='age',
            field=models.FloatField(),
        ),
    ]
